version: '2.1'

services:
  bitcored:
    build:
      context: ./docker-bitcored
      dockerfile: ./Dockerfile
    image: bitcored
    container_name: bitcore-rpc
    command:
      -externalip=51.15.77.33
      -whitebind=172.21.0.11:8555
      -rpcbind=172.21.0.11
      -maxconnections=64
      -rpcuser=btx-rpc-user
      -rpcpassword=btx-rpc-pwd
    restart: always
    networks:
      bitcore-net:
        ipv4_address: 172.21.0.11
    ports:
      - 8555:8555
    expose:
      - 8555
      - 8556
    volumes:
      - /home/bitcore:/data
    healthcheck:
      test: "bitcore-cli -datadir=/data -conf=/data/bitcore.conf -rpcconnect=172.21.0.11 -rpcuser=btx-rpc-user -rpcpassword=btx-rpc-pwd -rpcport=8556 mnsync status | grep MASTERNODE_SYNC_FINISHED"
      interval: 2m
      timeout: 1m
      retries: 60

  electrumx:
    image: dalijolijo/electrumx:1.14.0
    container_name: electrumx
    restart: always
    networks:
      bitcore-net:
        ipv4_address: 172.21.0.12
    ports:
      - 8000:8000
      - 50002:50002
    expose:
      - 8000
      - 50002
    volumes:
      - /home/bitcore:/data
    environment:
      DAEMON_URL: "http://btx-rpc-user:btx-rpc-pwd@172.21.0.11:8556"
      COIN: "Bitcore"
    depends_on:
      bitcored:
        condition: service_healthy

networks:
  bitcore-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

