version: '3'

services:
  bitcored:
    build:
      context: ./docker-bitcored
      dockerfile: ./Dockerfile
    image: bitcored
    container_name: bitcore-rpc
    command:
      -externalip=51.15.77.33
      -whitebind=172.21.0.11:8555
      -rpcbind=172.21.0.11
      -maxconnections=64
      -rpcuser=btx-rpc-user
      -rpcpassword=btx-rpc-pwd
    restart: always
    networks:
      bitcore-net:
        ipv4_address: 172.21.0.11
    ports:
      - 8555:8555
    expose:
      - 8555
      - 8556
    volumes:
      - /home/bitcore:/data

networks:
  bitcore-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
